import type { Meta, StoryObj } from "@storybook/react";
import { Button } from "./Button";
declare const meta: Meta<typeof Button>;
export default meta;
declare type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Ghost: Story;
export declare const Danger: Story;
export declare const Small: Story;
export declare const Pressed: Story;
export declare const Disabled: Story;
